name: myopinionrocks_app
description: Flutter App for MyOpinionRocks

version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #  provider: ^6.0.5
  dio: ^5.1.2
  package_info_plus: ^4.0.2
  device_info_plus: ^9.0.2
  shared_preferences: ^2.1.1
  easy_localization: ^3.0.1
  easy_localization_loader: ^1.0.1+1
  url_launcher: ^6.1.11
  auto_size_text: ^3.0.0
  badges: ^3.1.1
  flutter_secure_storage: ^8.0.0
  flutter_staggered_animations: ^1.1.1
  convex_bottom_bar: ^3.2.0
  path_provider: ^2.0.15
  tutorial_coach_mark: ^1.2.9
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
